#:schema https://mise.en.dev/schema/mise.json

[settings]
color = true
experimental = true
color_theme = "charm"

[tools]
fd = "latest"
bun = "latest"
node = "latest"
tombi = "latest"
shfmt = "latest"
shellcheck = "latest"
cloudflared = "latest"

[shell_alias]
oxfmt = "./node_modules/.bin/oxfmt"
oxlint = "./node_modules/.bin/oxlint"

[tasks.format]
description = "format files"
run = '''
shfmt --write --apply-ignore .
./node_modules/.bin/oxfmt format . --write
tombi format
'''

[tasks.lint]
description = "lint files"
run = '''
tombi lint
fd --extension sh --exclude skills --exec shellcheck
node_modules/.bin/oxlint --config='oxlint.config.ts' --type-aware --type-check --fix-dangerously
'''

[tasks.check]
description = "format & lint files"
depends = ["format"]
depends_post = ["lint"]
