name: Checks

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true
  WRANGLER_SEND_METRICS: false

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: "🔑 Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: "🐰 Setup Bun"
        uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: "Install Dependencies"
        run: bun install --frozen-lockfile

      - name: "Format & Lint & Type Check"
        run: |
          bun --bun oxfmt --config oxfmt.config.ts . --check
          bun --bun oxlint --config='oxlint.config.ts' --max-warnings=0
          bun tsgo --project tsconfig.json --noEmit

      - name: "Build"
        run: bun run build
